import Head from 'next/head'
import Image from 'next/image'




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='home'>
        <div className="hero">
          <div className='heroImg'>
            <img src="https://pemamerica.com/wp-content/uploads/2020/07/WhatsApp-Image-2020-07-23-at-9.04.59-PM-1.jpeg" alt="" />
          </div>
          <div className="info">
              <div>
              <img src="/images/logo-mona.png" alt="" />
              </div>
              <q>The world around us is constantly changing and so must we… Rising to these challenges together to achieve our goals.</q>

          </div>
        </div>
      </main>
     
    </>
  )
}
